plugins:
  - rubocop-rails
  - rubocop-factory_bot
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 3.2
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - "vendor/**/*"

Style/Documentation:
  Enabled: false

Style/ClassAndModuleChildren:
  EnforcedStyle: compact

Metrics/BlockLength:
  Exclude:
    - "spec/**/*"
    - "*.gemspec"
    - "lib/poly/joins.rb"

Metrics/AbcSize:
  Exclude:
    - "lib/poly/joins.rb"

Metrics/MethodLength:
  Exclude:
    - "lib/poly/joins.rb"

Metrics/ParameterLists:
  Max: 6

Rails/RakeEnvironment:
  Enabled: false

RSpec/MultipleExpectations:
  Max: 4
  Exclude:
    - "spec/models/poly/migration_spec.rb"

RSpec/ExampleLength:
  Max: 10
  Exclude:
    - "spec/models/poly/migration_spec.rb"
